from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd+'/inc']
LIBS = ['ISP583']
LIBPATH = [cwd]

group = DefineGroup('StdPeriphDriver', src, depend = [''],LIBS = LIBS, LIBPATH = LIBPATH, CPPPATH = CPPPATH)

Return('group')
