from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]
LIBS = ['CH58xBLE']
LIBPATH = [cwd]

group = DefineGroup('ble_lib', src, depend = [''],LIBS = LIBS, LIBPATH = LIBPATH, CPPPATH = CPPPATH)

Return('group')
